### ISSUE TITLE
Archived subdomains appear to be missing

### ISSUE THREAD

**Issue by beep** [alistapart/AListApart#125]
Per a quick chat with @murtaugh in Slack, it seems like the subdomains where we archived old versions of ALA are missing. For example, these links should show a previous version of the design/content:

http://v2.alistapart.com/articles/dao/
http://v2.alistapart.com/articles/responsive-web-design

But at the moment, they’re showing the current design/site.

**Comment by murtaugh** [comment]
Where did those v2 links come from? Looking at the server, we have a v4 folder, but not a v2 one. Which makes sense to me, because the previous version wasn’t the second version, it was the fourth. Versions older than that were lost before my time.

(FWIW, I found a link I posted to the previous design using the v4 domain.)

THAT HAVING BEEN SAID... v4.alistapart.com <http://v4.alistapart.com/> doesn’t work either, so I’ll have the host restore that.

**Comment by beep** [comment]
@murtaugh: Well, we had `v1.`, `v2.`, `v3.`, and `v4.` subdomains at one point. Maybe the first three got lost in the redesign? Not sure—sorry!

**Comment by murtaugh** [comment]
I have no memory of those, even from before the redesign, sorry. They would have been useful for tracking down missing content.

**Comment by murtaugh** [comment]
Just checked the old server, in case I was forgetting something, and there isn’t anything that looks like older versions. Looks like they went away prior to my joining ALA.

**Comment by murtaugh** [comment]
I've restored v4. I'll ask Jeffrey about v1, v2, and v3,but I suspect they are lost.

**Comment by beep** [comment]
Right on. Thanks for fixing v4, Tim!
