### ISSUE TITLE
Discuss creating a new authors channel

### ISSUE THREAD

**Issue by michellekondou** [alistapart/AListApart#133]

**Comment by murtaugh** [comment]
Context:

**Comment by murtaugh** [comment]
This is a low-priority, complex-to-enable wish of mine.

Context: 

1. The native members module is barely good enough for what we ask it to do, and templates that use member markup are a pain.
2. Made doubly a pain because to make some things easy, we have the User module, which can make marking up templates extra confusing.
3. With the new events, we're wanting to relate members to event channel entries in a way we've never done before. This would be made much simpler if people were standard channel entries.
