### ISSUE TITLE
"This article is not live yet" messaging is not showing up

### ISSUE THREAD

**Issue by murtaugh** [alistapart/AListApart#195]
The logic for this is here:

https://github.com/alistapart/AListApart/blob/components/templates/default_site/article.group/index.html#L130-L142

Something is up with Playa, I think. I just noticed the article date isn't showing up either.

**Comment by michellekondou** [comment]
It's not Playa. EE has become much stricter with the syntax for conditionals in the latest version. "The article is not live yet message" is not showing because the conditional is not evaluating correctly; the entry_date and current_date variables need to be wrapped in brackets for it to work. The article date is not showing because it's a future entry, and the show future entries parameter is not turned on in the specific loop that shows the date.
