### ISSUE TITLE
Add Smaller Description Deck

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#198]
The current description deck is too long for use in places like Related Content (or whatever we end up calling this section). 

Create an additional field called "mini-deck" with a short explanation/help text of "one-sentence description".

**Comment by murtaugh** [comment]
@sarawb: Can you confirm/correct my understanding of how the new Mini Deck works?

1. Articles, Blog Posts, and Columns all get this new field.
2. The content in the new field should replace the old deck wherever content is promoted, but not the main focus of the page — i.e. in the sidebar areas, but not the home page or blog/column landing pages. Do you want to use the new field in the emails as well?
3. To prevent holes, if the mini deck is not populated, the templates will fall back to the current field.

**Comment by sarawb** [comment]
1. Yes. 

2. Yes re: sidebars, etc. No for email (the full deck doesn't look long at all on email; I think the mini would look super spare). 

3. Yes, but should they (cringe) truncate in sidebars? 

Also, these should start pulling into Meta description, Open Graph Description, and Twitter Card description, instead of the full deck (per the recommendations from Jonathon).

**Comment by murtaugh** [comment]
Right, good call on the meta info.

3. We *could* truncate, if you think it's the lesser of two evils. I would lean toward showing the whole thing, my thinking being that the larger text might be more likely to draw the attention of an editor who will realize the mini deck empty.

**Comment by michellekondou** [comment]
@aparkening @murtaugh @sarawb 
I have implemented this on DEV, the mini-deck field has been populated in a few recent cases so we can see how it works and looks. Let me list the cases where we see the mini-deck:
1) Articles landing page in the sidebar only (for column + blog entries)
2) Columns landing page in the sidebar only (for article + blog entries)
3) Article entry pages in the sidebar (for column + blog entries)
4) Column entry pages in the sidebar (for column + blog entries)
5) Blog entry pages in the sidebar (for column + blog entries)

Shouldn't we be also be showing articles in all the sidebars or will this be covered by the new relationships fields?

**Comment by sarawb** [comment]
> We could truncate, if you think it's the lesser of two evils. I would lean toward showing the whole thing, my thinking being that the larger text might be more likely to draw the attention of an editor who will realize the mini deck is empty.

I think there should be zero excuse for leaving this empty for new articles—this will be on the list of required details, and we'll have Erin checking that it's there in prod for articles. 

What I am worried about is the vast amount of past articles we are dealing with. So let's say we have a new article on RWD we publish. Of course the editor will write a mini-deck for that. But the new article template will pull in a couple recent RWD articles that might predate the mini-deck. If that uses the full deck instead, then the template will look pretty overloaded. And I suspect, at least at first, that that will happen quite often. That's not something an editor can be expected to do: go back to the past pieces and write new mini-decks for all of them. So that's why I think a truncation fallback might be the most realistic.

**Comment by murtaugh** [comment]
Ok cool, we will truncate.

Maybe we could (someday) make it a community task to add mini decks to older content.

**Comment by michellekondou** [comment]
@sarawb @murtaugh @aparkening 
I implemented truncating (you can see examples on [DEV] (dev.alistapart.com) in the same places listed above where we are using the mini-deck). I set the description to truncate at 175 characters and to end with '...' Is the number of characters ok and should we use an elipsis?

**Comment by sarawb** [comment]
175 chars and an ellipsis works for me! Thanks @michellekondou!

**Comment by michellekondou** [comment]
@aparkening @sarawb @murtaugh 
The mini deck is now pulling into Meta description, Open Graph Description, and Twitter Card description (if there isn't one the full deck is being used). Any second thoughts before we push these changes to production? Double checking because it will a visible change in the page layout.

**Comment by sarawb** [comment]
I think we're set on my end. This means we need to be aggressive about having editors use the new field starting now! I'll finish up some guidelines for that.
