### ISSUE TITLE
RSS sponsorships not showing up

### ISSUE THREAD

**Issue by marieconnelly** [alistapart/AListApart#211]
The last two weeks of sponsorship posts are set to open in the CMS, but I haven't seen them in my ALA RSS feed on Feedly, and I'm not seeing anything here: http://feeds.feedburner.com/alistapart/main

**Comment by murtaugh** [comment]
I'm going to ask @michellekondou to take a look at this as soon as she can. This keeps happening, and I don't know why.

In the past it has been Feedburner's cache sticking, or readers not wanting to show posts with the same title or URL, but those don't seem to be the case here.

**Comment by marieconnelly** [comment]
Thanks, Tim. We're hoping to catch up on the posts that got missed, and have another post to go out this week, so it'd be ideal to get this figured out as soon as we can.

**Comment by murtaugh** [comment]
@marieconnelly: Michelle and I figured it out. RSS Sponsorship entries were originally set up to expire after a week, but the Pantheon one for some reason expired before it even went live. You can see the dates here:

http://dev.alistapart.com/test

(Are you sure the Inbound.org one never showed? Because it looks like it has good dates.)

So, the puzzle is, why did the Pantheon post expire so early? Do you recall if you set this one up differently somehow (like much earlier than usual)?

In any case, we recently removed the feature that auto-expires the entries, so this won't happen going forward.

**Comment by murtaugh** [comment]
@marieconnelly: The other question is: how do you want to handle the Pantheon post?

**Comment by marieconnelly** [comment]
Ah-HA! So, that does makes sense with Pantheon—I had scheduled them a week early, not knowing the posts expired after a week. Is it possible this somehow impacted the Inbound post? I'm definitely not seeing it in either of the feeds I have access to.

**Comment by murtaugh** [comment]
The Inbound one expired at the normal time, a week after it was posted — are you sure it wasn't showing up during it's non-expired time?

**Comment by michellekondou** [comment]
We made the expiration date field visible in the edit page, so you can change it yourself now!

**Comment by marieconnelly** [comment]
@murtaugh Hmm. I'm not sure, Feedly seems to be showing _some_ past sponsors in my feed (Flywheel, Beagle) but not all of them. Perhaps it has to do with whether the post was read before it expired? What's the impetus for expiring these posts?

**Comment by murtaugh** [comment]
Hm, I'm going to guess that Feedly is caching the older ones. I have no idea why Feedly would store some and not others, and I'm sure every reader is different, so the whole expiring thing was probably a somewhat useless exercise since people maybe have been seeing them anyway :/

**Comment by michellekondou** [comment]
I'm closing this, @marieconnelly I see the sponsorships are appearing in the feed as expected.
