### ISSUE TITLE
Redirect ALA subdomains to www

### ISSUE THREAD

**Issue by aparkening** [alistapart/AListApart#317]
As per duckduck's search results, we should redirect all subdomains to www.
![duckduck-search](https://cloud.githubusercontent.com/assets/7241111/11222875/ee55c68c-8d3a-11e5-812a-79251cdbf9ff.png)

**Comment by murtaugh** [comment]
Clarification: wildcard subdomains should redirect to no subdomain. At some point in the future we will switch to www.

**Comment by michellekondou** [comment]
This issue is related to this https://github.com/alistapart/AListApart/issues/146 which I had closed back in the beginning of October. It seems I overwrote that redirect rule -  a lot is going on in our .htaccess file. I'm closing this again, I've tested extensively. I check webmaster tools crawl errors every other day and things seem quite normal.

**Comment by aparkening** [comment]
Thanks Michelle!
