### ISSUE TITLE
Website cut off

### ISSUE THREAD

**Issue by MelissaSims** [alistapart/AListApart#333]
The top and bottom of the website are cut off on my screen. I'm using Google Chrome Version 46.0.2490.86 m

**Comment by aparkening** [comment]
Thanks for letting us know about the top and bottom of the website getting cut off in Chrome, @MelissaSims.  We're investigating, and we'll let you know when it's fixed!

**Comment by aparkening** [comment]
Hi @MelissaSims.  I think I initially misunderstood your bug report -- just in case you're referring to the cut off logotype ("A List Apart") and footer text ("*For People Who Make Websites"), those are design choices, rather than layout bugs.  If you're referring to something else, please let me know.

I did notice incorrect whitespace below the footer text while reviewing this issue, so we'll update the site to remove that.

Please let us know if you spot any other issues!
