### ISSUE TITLE
Twitter bio link broken in author profile – current article

### ISSUE THREAD

**Issue by zeldman** [alistapart/AListApart#373]
The author bio (http://alistapart.com/author/orr-shtuhl) for yesterday’s article contains a non-functioning Twitter link. The link reads ”@orr-shtuhl” but apparently points to Twitter’s home page instead of pointing to http://alistapart.com/author/orr-shtuhl as it should. As a result, clicking the author’s Twitter bio link merely loads the Twitter home page instead of the author’s Twitter profile page.
![safarisnaps002](https://cloud.githubusercontent.com/assets/2983799/14493854/c967c606-0155-11e6-9adc-bf998f93281d.png)

**Comment by michellekondou** [comment]
Corrected! Theses issues are a result of a big change we made: pulling information for authors from the contributor channel instead of the member module.

**Comment by zeldman** [comment]
Thanks! Is it fixed everywhere? Is the info in the contributor channel
incorrect?

…………………………………

Jeffrey Zeldman

A Space Apart

148 Madison Avenue, Suite 600

New York, NY 10016

917-746-4838


A Book Apart <http://abookapart.com> | A List Apart <http://alistapart.com/>
 | An Event Apart <http://aneventapart.com>

Big Web Show <http://5by5.tv/bigwebshow> | zeldman.com <http://Zeldman.com>
| @zeldman <https://twitter.com/zeldman>

**Comment by michellekondou** [comment]
It is fixed everywhere. The info in the contributor is correct. 
The goal is to only fill in author infomation in one place (the contributor channel) instead of both the contributor channel and the member module. I have been working with Erin to discover any instances where the info might still be getting pulled from the member module instead of the contributor channel. It is correct everywhere because up to now we had been filling in information in both places, which ofcourse is counterproductive!

**Comment by zeldman** [comment]
THANK YOU so much! I understand completely, and greatly appreciate what
you've done and are doing.


…………………………………

Jeffrey Zeldman

A Space Apart

148 Madison Avenue, Suite 600

New York, NY 10016

917-746-4838


A Book Apart <http://abookapart.com> | A List Apart <http://alistapart.com/>
 | An Event Apart <http://aneventapart.com>

Big Web Show <http://5by5.tv/bigwebshow> | zeldman.com <http://Zeldman.com>
| @zeldman <https://twitter.com/zeldman>
