### ISSUE TITLE
Different dates showing for same article

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#385]
The date for this article is July 27, 2001 on the article page: http://alistapart.com/article/Process

but August 20, 2005 on her bio page: http://alistapart.com/author/meryl-k-evans

**Comment by michellekondou** [comment]
@m1ca: Legacy articles (that belong to an issue) show the date of the issue they belong to on the article page; that specific article is assigned to issue 118, which has a date of  7/27/2001 (http://alistapart.com/issue/118 -  it doesn't have an illustration assigned). 

Normally legacy articles should have the issue date assigned to them. So, this article: http://alistapart.com/article/Process, should have a date of 7/27/2001. 
That is the case with the legacy articles dating back to issue 231 (dated 1/21/2007, title Paper Prototyping and Quick CSS Mockups with Photoshop). Before that period, legacy articles dates are all wonky (different from the issue date), I assume due to some database migration or change of content strategy.

Correcting the bio page to show the issue date for legacy articles (instead of the article date) would add a lot of unneccessary processing overhead - plus it seems to me that what should be corrected are the legacy article dates; all the more since we ditched issues.  

I'll check the database to see how issue and article dates are connected, so we can make the change in the DB in batches.

What do you think? Isn't it better to correct the article dates?

**Comment by michellekondou** [comment]
@m1ca @murtaugh @zeldman 

I shared a spreadsheet with you containing old issues and corresponding articles and their dates, which highlights the differences between article and issue date.

I wrote a script to update the old article dates to correspond to the issue dates, shall I run it? 
Don't we want to change the article date to correspond to the issue date?

**Comment by m1ca** [comment]
@michellekondou @murtaugh @zeldman 

Michelle, yes, please update the article dates to match the issue dates. I just did a data sort on the spreadsheet and see lots of heavily-replicated article dates that are totally wrong.

**Comment by michellekondou** [comment]
Ok, will do on Monday, I'll be travelling tomorrow

**Comment by michellekondou** [comment]
@m1ca @murtaugh 
I changed the article dates on DEV, (e.g. http://dev.alistapart.com/author/meryl-k-evans); everything seems to be fine. 
I'll change them in production tomorrow morning my time (night time in the US) which is a low traffic hour just to be sure.

**Comment by michellekondou** [comment]
@zeldman @m1ca @murtaugh 

I have updated the spreadsheet to be easier to scan; Jeffrey you should probably go through those dates, so we're sure before I go updating our Database.

**Comment by zeldman** [comment]
I have not seen a shared spreadsheet. Was it shared via email? Basecamp?

**Comment by zeldman** [comment]
Hi, @m1ca @michellekondou @murtaugh (the 3 M's!)

I've looked at the spreadsheet but am not sure I understand it. Article dates and issue dates should always match. Always. When there is a discrepancy, my guess is that the earlier date is usually correct, i.e. "The Ins and Outs of Intranets" has a 2000 date and a 2005 date. I'm sure the earlier (2000) date is correct.

I cannot account for discrepancies or verify that any of these dates is correct. I can tell you that the issue dates and the article dates should match. That is all I can tell you.

You folks seem to have a much better handle on this than I do. Carry on, I guess?

**Comment by michellekondou** [comment]
@m1ca @zeldman @murtaugh 
It's done! Article dates have been corrected :)
