### ISSUE TITLE
Date display problems on old articles 

### ISSUE THREAD

**Issue by sarawb** [alistapart/AListApart#89]
Was looking for something in the archives and noticed that the dates on the /articles pages aren't matching the dates on the articles themselves. Click pretty much anything here: http://alistapart.com/articles/archives/190 and you'll see that the article lists a different date. 

For example: 
![image](https://cloud.githubusercontent.com/assets/3171996/3866898/1ed645d8-1fe7-11e4-9fb5-350ac7975fcb.png)

And then: 

![image](https://cloud.githubusercontent.com/assets/3171996/3866899/2a74e4b2-1fe7-11e4-9dd0-555707a71ddd.png)

![image](https://cloud.githubusercontent.com/assets/3171996/3866904/83e8bdac-1fe7-11e4-90ef-34c8eb2a394f.png)

This seems to be happening across a ton of content from 2005-2007. Not sure which date is even the correct date...

**Comment by murtaugh** [comment]
@michellekondou: a note that might be useful: wherever an article date is displayed, we actually want to display the *issue* date. This allows us to only have to manage the date on one entry in the system. The articles usually have the same date anyway, but for the sake of consistency, the issue date should be shown. Perhaps some of the templates aren't properly displaying the issue date?

(As for the accuracy of the dates, I would lean toward assuming the issue dates are correct, since that's what we historically publish. If we think some of them are wrong, auditing those is a bigger job that might be suitable for possible volunteer-driven Wayback research? cc: @sarawb)

**Comment by michellekondou** [comment]
The article page shows the correct date (the issue date). The archives template was displaying the entry date instead of the issue date (it seems that in the older entries entry date != issue date). I changed it to display the issue date. 
@murtaugh The query does add a slight overhead though (1s). I'm wondering whether it's not more correct to show the date once, next to the issue # (since it's the issue date) instead of showing the same issue date for each article (which also does not add the extra 1s for the query).

**Comment by murtaugh** [comment]
Is this a concern once the page has been loaded once? The whole site goes through CloudFlare, so everything is cached.

**Comment by michellekondou** [comment]
No it's not,
